# file: docker-compose.yml
#        author: Thus0
# last modified: 2022-01-30 20:30

version: "3.9"

services:

  #
  # router-coap
  #
  router-coap:
    build: router
    container_name: router-coap
    privileged: true
    cap_add:
      - NET_ADMIN
      - NET_RAW
    networks:
      operator_net:
        ipv4_address: 192.168.12.254
      inter_net:
        ipv4_address: 192.168.11.254
    restart: unless-stopped
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv6.conf.all.disable_ipv6=1
    volumes:
      - "./share/dumps:/app/dumps"

  #
  # client-aiocoap
  #
  client-aiocoap:
    build:
      context: ./aiocoap
      target: client
    container_name: client-aiocoap
    cap_add:
      - NET_ADMIN
    environment:
      DTLS_SERVER: 192.168.11.101
      DTLS_PORT: 5684
      GATEWAY: 192.168.12.254
    volumes:
      - "./share/dumps:/app/dumps"
    networks:
      operator_net:
        ipv4_address: 192.168.12.3

  #
  # client-libcoap
  #
  client-libcoap:
    build:
      context: ./libcoap
      target: client
    container_name: client-libcoap
    cap_add:
      - NET_ADMIN
    environment:
      DTLS_SERVER: 192.168.11.101
      DTLS_PORT: 5684
      GATEWAY: 192.168.12.254
    volumes:
      - "./share/dumps:/app/dumps"
    networks:
      operator_net:
        ipv4_address: 192.168.12.4

  #
  # client-coap-cli
  #
  client-coap-cli:
    build: coap-cli
    container_name: client-coap-cli
    cap_add:
      - NET_ADMIN
    environment:
      DTLS_SERVER: 192.168.11.101
      DTLS_PORT: 5684
      GATEWAY: 192.168.12.254
    volumes:
      - "./share/dumps:/app/dumps"
    networks:
      operator_net:
        ipv4_address: 192.168.12.5

  #
  # client-californium
  #
  client-californium:
    build:
      context: ./californium
      target: client
    container_name: client-californium
    cap_add:
      - NET_ADMIN
    environment:
      DTLS_SERVER: 192.168.11.106
      DTLS_PORT: 5684
      GATEWAY: 192.168.12.254
    volumes:
      - "./share/dumps:/app/dumps"
    networks:
      operator_net:
        ipv4_address: 192.168.12.6

  #
  # client-gnutls
  #
  client-gnutls:
    build:
      context: ./gnutls
      target: client
    container_name: client-gnutls
    cap_add:
      - NET_ADMIN
    environment:
      DTLS_SERVER: 192.168.11.107
      DTLS_PORT: 5684
      GATEWAY: 192.168.12.254
    volumes:
      - "./share/dumps:/app/dumps"
    networks:
      operator_net:
        ipv4_address: 192.168.12.7

  #
  # client-mbedtls
  #
  client-mbedtls:
    build:
      context: ./mbedtls
      target: client
    container_name: client-mbedtls
    cap_add:
      - NET_ADMIN
    environment:
      DTLS_SERVER: 192.168.11.108
      DTLS_PORT: 5684
      GATEWAY: 192.168.12.254
    volumes:
      - "./share/dumps:/app/dumps"
    networks:
      operator_net:
        ipv4_address: 192.168.12.8
  
  #
  # client-wolfssl
  #
  client-wolfssl:
    build:
      context: ./wolfssl
      target: client
    container_name: client-wolfssl
    cap_add:
      - NET_ADMIN
    environment:
      DTLS_SERVER: 192.168.11.109
      DTLS_PORT: 5684
      GATEWAY: 192.168.12.254
    volumes:
      - "./share/dumps:/app/dumps"
    networks:
      operator_net:
        ipv4_address: 192.168.12.9

  #
  # client-tinydtls
  #
  client-tinydtls:
    build:
      context: ./tinydtls
      target: client
    container_name: client-tinydtls
    cap_add:
      - NET_ADMIN
    environment:
      DTLS_SERVER: 192.168.11.110
      DTLS_PORT: 5684
      GATEWAY: 192.168.12.254
    volumes:
      - "./share/dumps:/app/dumps"
    networks:
      operator_net:
        ipv4_address: 192.168.12.10
  
  #
  # client-boringssl
  #
  client-boringssl:
    build:
      context: ./boringssl
      target: client
    container_name: client-boringssl
    cap_add:
      - NET_ADMIN
    environment:
      DTLS_SERVER: 192.168.11.111
      DTLS_PORT: 5684
      GATEWAY: 192.168.12.254
    volumes:
      - "./share/dumps:/app/dumps"
    networks:
      operator_net:
        ipv4_address: 192.168.12.11

  #
  # client-freecoap
  #
  client-freecoap:
    build:
      context: ./freecoap
      target: client
    container_name: client-freecoap
    cap_add:
      - NET_ADMIN
    environment:
      DTLS_SERVER: 192.168.11.112
      DTLS_PORT: 5684
      GATEWAY: 192.168.12.254
    volumes:
      - "./share/dumps:/app/dumps"
    networks:
      operator_net:
        ipv4_address: 192.168.12.12

  #
  # server-thingsboard
  #
  server-thingsboard:
    restart: always
    image: thingsboard/tb-postgres:3.3.3
    container_name: server-thingsboard
    cap_add:
      - NET_ADMIN
    ports:
      - 9090:9090
      - 1883:1883   # MQTT
      - 8883:8883   # MQTTS
      - 7070:7070
      - 5683-5688:5683-5688/udp
    # https://thingsboard.io/docs/user-guide/install/config/
    environment:
      COAP_DTLS_ENABLED: true
      COAP_DTLS_CREDENTIALS_TYPE: "PEM"
      COAP_DTLS_PEM_CERT: "ssl/thingsboard.pem"
      COAP_DTLS_PEM_KEY: "ssl/thingsboard.key"
      COAP_DTLS_BIND_PORT: 5684
      TB_COAP_X509_DTLS_SKIP_VALIDITY_CHECK_FOR_CLIENT_CERT: false
      COAP_X509_DTLS_SKIP_VALIDITY_CHECK_FOR_CLIENT_CERT: false
      TB_COAP_X509_DTLS_SESSION_INACTIVITY_TIMEOUT: 86400000
      COAP_X509_DTLS_SESSION_INACTIVITY_TIMEOUT: 86400000
      TB_COAP_X509_DTLS_SESSION_REPORT_TIMEOUT: 1800000
      COAP_X509_DTLS_SESSION_REPORT_TIMEOUT: 1800000
      MQTT_SSL_ENABLED: true
      MQTT_SSL_CREDENTIALS_TYPE: "PEM"
      MQTT_SSL_PEM_CERT: "ssl/thingsboard.pem"
      MQTT_SSL_PEM_KEY: "ssl/thingsboard.key"
      MQTT_SSL_BIND_PORT: 8883
      MQTT_SSL_PROTOCOL: "TLSv1.2"
      MQTT_SSL_SKIP_VALIDITY_CHECK_FOR_CLIENT_CERT: false  
    volumes:
      - "./thingsboard/data:/data"
      - "./thingsboard/log:/var/log/thingsboard"
      - "./thingsboard/conf:/usr/share/thingsboard/conf"
      - "./share/dumps:/app/dumps"
    networks:
      inter_net:
        ipv4_address: 192.168.11.101

  #
  # server-aiocoap
  #
  server-aiocoap:
    build:
      context: ./aiocoap
      target: server
    container_name: server-aiocoap
    cap_add:
      - NET_ADMIN
    volumes:
      - "./share/dumps:/app/dumps"
    networks:
      inter_net:
        ipv4_address: 192.168.11.103

  #
  # server-libcoap
  #
  server-libcoap:
    build:
      context: ./libcoap
      target: server
    container_name: server-libcoap
    cap_add:
      - NET_ADMIN
    volumes:
      - "./share/dumps:/app/dumps"
    networks:
      inter_net:
        ipv4_address: 192.168.11.104
  
  #
  # server-californium
  #
  server-californium:
    build:
      context: ./californium
      target: server
    container_name: server-californium
    cap_add:
      - NET_ADMIN
    volumes:
      - "./share/dumps:/app/dumps"
    networks:
      inter_net:
        ipv4_address: 192.168.11.106
  
  #
  # server-gnutls
  #
  server-gnutls:
    build:
      context: ./gnutls
      target: server
    container_name: server-gnutls
    cap_add:
      - NET_ADMIN
    volumes:
      - "./share/dumps:/app/dumps"
    networks:
      inter_net:
        ipv4_address: 192.168.11.107

  #
  # server-mbedtls
  #
  server-mbedtls:
    build:
      context: ./mbedtls
      target: server
    container_name: server-mbedtls
    cap_add:
      - NET_ADMIN
    volumes:
      - "./share/dumps:/app/dumps"
    networks:
      inter_net:
        ipv4_address: 192.168.11.108

  #
  # server-wolfssl
  #
  server-wolfssl:
    build:
      context: ./wolfssl
      target: server
    container_name: server-wolfssl
    cap_add:
      - NET_ADMIN
    volumes:
      - "./share/dumps:/app/dumps"
    networks:
      inter_net:
        ipv4_address: 192.168.11.109

  #
  # server-tinydtls
  #
  server-tinydtls:
    build:
      context: ./tinydtls
      target: server
    container_name: server-tinydtls
    cap_add:
      - NET_ADMIN
    volumes:
      - "./share/dumps:/app/dumps"
    networks:
      inter_net:
        ipv4_address: 192.168.11.110

  #
  # server-boringssl
  #
  server-boringssl:
    build:
      context: ./boringssl
      target: server
    container_name: server-boringssl
    cap_add:
      - NET_ADMIN
    volumes:
      - "./share/dumps:/app/dumps"
    networks:
      inter_net:
        ipv4_address: 192.168.11.111

  #
  # server-freecoap
  #
  server-freecoap:
    build:
      context: ./freecoap
      target: server
    container_name: server-freecoap
    cap_add:
      - NET_ADMIN
    volumes:
      - "./share/dumps:/app/dumps"
    networks:
      inter_net:
        ipv4_address: 192.168.11.112

  #
  # server-emqx
  #
  server-emqx:
    image: emqx/emqx:latest
    container_name: server-emqx
    environment:
      - "EMQX_NAME=server-emqx"
    ports:
      - 8081:8081     # http.management
      - 18083:18083   # http.dashboard
      - 1883:1883     # mqtt:tcp
      - 5683:5683     # coap:udp
      - 5684:5684     # coap:dtls
      - 8883:8883     # mqtt:tls
    volumes:
      - "./emqx/data:/opt/emqx/data"
      - "./emqx/etc:/opt/emqx/etc"
      - "./emqx/log:/opt/emqx/log"
      - "./share/dumps:/app/dumps"
    networks:
      inter_net:
        ipv4_address: 192.168.11.113

###

###
### sensor  --- [operator_net] ------- router-bts ------- [inter_net] ------- server
###              192.168.12.x         .254    .254       192.168.11.x 

networks:
    operator_net:
      driver: bridge
      enable_ipv6: false
      ipam:
        driver: default
        config:
          - subnet: 192.168.12.0/24
            gateway: 192.168.12.254
    inter_net:
      driver: bridge
      enable_ipv6: false
      ipam:
        driver: default
        config:
          - subnet: 192.168.11.0/24
            gateway: 192.168.11.1

